feat: add vab and kustomize to kubernetes image

diff --git a/containers/kubernetes/Dockerfile b/containers/kubernetes/Dockerfile
--- a/containers/kubernetes/Dockerfile
+++ b/containers/kubernetes/Dockerfile
@@ -9,15 +9,25 @@ ARG KUBECTL_VERSION=v1.32.3
 ARG KUBECTL_CHECKSUM=ab209d0c5134b61486a0486585604a616a5bb2fc07df46d304b3c95817b2d79f
 ARG KUBECTL_CHECKSUM_ARM=6c2c91e760efbf3fa111a5f0b99ba8975fb1c58bb3974eca88b6134bcf3717e2
 
-# https://github.com/mia-platform/mlp/releases
-ARG MLP_VERSION=v2.0.0
-ARG MLP_CHECKSUM=ae28c70851301e97ad9e09d7dc2f205b6fd6659e14641ef6e38eb30c6742809c
-ARG MLP_CHECKSUM_ARM=6cea7433f6cb5a28fde08ebaee38cf47b4836e5d8554cd5a6ee444d6c354ede8
+# https://github.com/kubernetes-sigs/kustomize/releases
+ARG KUSTOMIZE_VERSION=v5.6.0
+ARG KUSTOMIZE_CHECKSUM=54e4031ddc4e7fc59e408da29e7c646e8e57b8088c51b84b3df0864f47b5148f
+ARG KUSTOMIZE_CHECKSUM_ARM=ad8ab62d4f6d59a8afda0eec4ba2e5cd2f86bf1afeea4b78d06daac945eb0660
 
 # https://github.com/helm/helm/releases
 ARG HELM_VERSION=v3.17.2
 ARG HELM_CHECKSUM=90c28792a1eb5fb0b50028e39ebf826531ebfcf73f599050dbd79bab2f277241
 ARG HELM_CHECKSUM_ARM=d78d76ec7625a94991e887ac049d93f44bd70e4876200b945f813c9e1ed1df7c
+
+# https://github.com/mia-platform/mlp/releases
+ARG MLP_VERSION=v2.0.1
+ARG MLP_CHECKSUM=f0384abb757f655b215d5b22e278f0063dfb47d1ee9738ef7b5facbdf8cd47ac
+ARG MLP_CHECKSUM_ARM=351c0dec0f04c1fd3eec8120de4427317d0b2da9ccd0b43ce9f601e979ab36ec
+
+# https://github.com/mia-platform/vab/releases
+ARG VAB_VERSION=v0.12.1
+ARG VAB_CHECKSUM=e708276b2dff19a4e8bdab50b0e71adb1a887a6c9581801cec02dd2c9a6f03aa
+ARG VAB_CHECKSUM_ARM=07624a8135243b6b6282b44a56678ef902056b50b9c2e5e53e1343f47e3134c8
 
 USER root
 
@@ -38,16 +48,17 @@ RUN case "${TARGETARCH}" in \
 
 RUN case "${TARGETARCH}" in \
 		'amd64') \
-			mlp_checksum="${MLP_CHECKSUM}"; \
+			kustomize_checksum="${KUSTOMIZE_CHECKSUM}"; \
 		;; \
 		'arm64') \
-			mlp_checksum="${MLP_CHECKSUM_ARM}"; \
+			kustomize_checksum="${KUSTOMIZE_CHECKSUM_ARM}"; \
 	;; \
 		*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
 	esac; \
-	curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/mia-platform/mlp/releases/download/${MLP_VERSION}/mlp-linux-${TARGETARCH}" -o "/tmp/mlp" \
-	&& echo "${mlp_checksum} /tmp/mlp" | sha256sum -c \
-	&& install -o "root" -g "root" -m "0755" "/tmp/mlp" "/tmp/local/bin/mlp"
+	curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_${TARGETARCH}.tar.gz" -o "/tmp/kustomize.tar.gz" \
+	&& echo "${kustomize_checksum} /tmp/kustomize.tar.gz" | sha256sum -c \
+	&& tar -xvf "/tmp/kustomize.tar.gz" --no-same-permissions --no-same-owner -C "/tmp" \
+	&& install -o "root" -g "root" -m "0755" "/tmp/kustomize" "/tmp/local/bin/kustomize"
 
 RUN case "${TARGETARCH}" in \
 		'amd64') \
@@ -62,6 +73,32 @@ RUN case "${TARGETARCH}" in \
 	&& echo "${helm_checksum} /tmp/helm.tar.gz" | sha256sum -c \
 	&& tar -xvf "/tmp/helm.tar.gz" --no-same-permissions --no-same-owner -C "/tmp" \
 	&& install -o "root" -g "root" -m "0755" "/tmp/linux-${TARGETARCH}/helm" "/tmp/local/bin/helm"
+
+RUN case "${TARGETARCH}" in \
+		'amd64') \
+			mlp_checksum="${MLP_CHECKSUM}"; \
+		;; \
+		'arm64') \
+			mlp_checksum="${MLP_CHECKSUM_ARM}"; \
+	;; \
+		*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
+	esac; \
+	curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/mia-platform/mlp/releases/download/${MLP_VERSION}/mlp-linux-${TARGETARCH}" -o "/tmp/mlp" \
+	&& echo "${mlp_checksum} /tmp/mlp" | sha256sum -c \
+	&& install -o "root" -g "root" -m "0755" "/tmp/mlp" "/tmp/local/bin/mlp"
+
+RUN case "${TARGETARCH}" in \
+		'amd64') \
+			vab_checksum="${VAB_CHECKSUM}"; \
+		;; \
+		'arm64') \
+			vab_checksum="${VAB_CHECKSUM_ARM}"; \
+	;; \
+		*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
+	esac; \
+	curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/mia-platform/vab/releases/download/${VAB_VERSION}/vab-linux-${TARGETARCH}" -o "/tmp/vab" \
+	&& echo "${vab_checksum} /tmp/vab" | sha256sum -c \
+	&& install -o "root" -g "root" -m "0755" "/tmp/vab" "/tmp/local/bin/vab"
 
 FROM ghcr.io/mia-platform/base-pipeline:1
 
