feat: update installed tools

diff --git a/containers/base/Dockerfile b/containers/base/Dockerfile
--- a/containers/base/Dockerfile
+++ b/containers/base/Dockerfile
@@ -13,6 +13,11 @@ ARG SYFT_VERSION=1.20.0
 ARG SYFT_CHECKSUM=689e12c5cbf67521ce61b9c126068f9eaabe1223e77971b2fede50033ff6b5cc
 ARG SYFT_CHECKSUM_ARM=53f76737ddbf425c89240d5b0be0990b1a71e66890b44f19743221b17e6ee635
 
+# https://github.com/oras-project/oras/releases
+ARG ORAS_VERSION=1.2.2
+ARG ORAS_CHECKSUM=bff970346470e5ef888e9f2c0bf7f8ee47283f5a45207d6e7a037da1fb0eae0d
+ARG ORAS_CHECKSUM_ARM=edd7195cbb8ba56c29ede413eefa10c8026201d63326017cd315841b4063aa56
+
 USER root
 
 RUN mkdir -p "/tmp/local/bin" "/tmp/local/lib"
@@ -43,6 +48,20 @@ RUN case "${TARGETARCH}" in \
 	&& echo "${syft_checksum} /tmp/syft.tar.gz" | sha256sum -c \
 	&& tar -xvf "/tmp/syft.tar.gz" --no-same-permissions --no-same-owner -C "/tmp" \
 	&& install -o "root" -g "root" -m "0755" "/tmp/syft" "/tmp/local/bin/syft"
+
+RUN case "${TARGETARCH}" in \
+	'amd64') \
+		checksum="${ORAS_CHECKSUM}"; \
+	;; \
+	'arm64') \
+		checksum="${ORAS_CHECKSUM_ARM}"; \
+	;; \
+	*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
+esac; \
+curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/oras-project/oras/releases/download/v${ORAS_VERSION}/oras_${ORAS_VERSION}_linux_${TARGETARCH}.tar.gz" -o "/tmp/oras.tar.gz" \
+&& echo "${checksum} /tmp/oras.tar.gz" | sha256sum -c \
+&& tar -xvf "/tmp/oras.tar.gz" --no-same-permissions --no-same-owner -C "/tmp" \
+&& install -o "root" -g "root" -m "0755" "/tmp/oras" "/tmp/local/bin/oras"
 
 COPY ./base_helpers.sh /tmp/local/lib
 
diff --git a/containers/docker/Dockerfile b/containers/docker/Dockerfile
--- a/containers/docker/Dockerfile
+++ b/containers/docker/Dockerfile
@@ -7,14 +7,14 @@ ARG TARGETARCH
 ARG DOCKER_VERSION=28.0.1
 
 # https://github.com/docker/buildx/releases
-ARG BUILDX_VERSION=v0.21.1
-ARG BUILDX_CHECKSUM=7f355525bfaf411302570b705118181b720f18071f4be3f0eaac7b2297d826e2
-ARG BUILDX_CHECKSUM_ARM=42d5cee287ec7426de5252276a05f3ea565ac2d65d62d052b885a84dd54152d5
+ARG BUILDX_VERSION=v0.21.2
+ARG BUILDX_CHECKSUM=b13bee81c3db12a4be7d0b9d042b64d0dd9ed116f7674dfac0ffdf2a71acfe3d
+ARG BUILDX_CHECKSUM_ARM=7e21e62eae3243e476411c9bbe93b8ee59b5d62ddf075c527d168174c3ab3a04
 
-# https://github.com/oras-project/oras/releases
-ARG ORAS_VERSION=1.2.2
-ARG ORAS_CHECKSUM=bff970346470e5ef888e9f2c0bf7f8ee47283f5a45207d6e7a037da1fb0eae0d
-ARG ORAS_CHECKSUM_ARM=edd7195cbb8ba56c29ede413eefa10c8026201d63326017cd315841b4063aa56
+# https://github.com/docker/compose/releases
+ARG DOCKER_COMPOSE_VERSION=v2.33.1
+ARG DOCKER_COMPOSE_CHECKSUM=3efda1ad6caed49dedd5644cadbf7e0c9cc3d74d8844ca5237b6a43ac1ef1a46
+ARG DOCKER_COMPOSE_CHECKSUM_ARM=fa0e077510c852237b0da426d0daf6853446e7760145ce7665ec401892a4d0de
 
 USER root
 
@@ -27,30 +27,32 @@ RUN arch="$(uname -m)"; \
 
 RUN case "${TARGETARCH}" in \
 		'amd64') \
-			checksum="${BUILDX_CHECKSUM}"; \
+			buildx_checksum="${BUILDX_CHECKSUM}"; \
 		;; \
 		'arm64') \
-			checksum="${BUILDX_CHECKSUM_ARM}"; \
+			buildx_checksum="${BUILDX_CHECKSUM_ARM}"; \
 		;; \
 		*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
 	esac; \
 	curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-${TARGETARCH}" -o "/tmp/docker-buildx" \
-	&& echo "${checksum} /tmp/docker-buildx" | sha256sum -c \
+	&& echo "${buildx_checksum} /tmp/docker-buildx" | sha256sum -c \
 	&& install -o "root" -g "root" -m "0755" "/tmp/docker-buildx" "/tmp/local/lib/docker/cli-plugins/docker-buildx"
 
-RUN case "${TARGETARCH}" in \
-		'amd64') \
-			checksum="${ORAS_CHECKSUM}"; \
-		;; \
-		'arm64') \
-			checksum="${ORAS_CHECKSUM_ARM}"; \
-		;; \
-		*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
-	esac; \
-	curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/oras-project/oras/releases/download/v${ORAS_VERSION}/oras_${ORAS_VERSION}_linux_${TARGETARCH}.tar.gz" -o "/tmp/oras.tar.gz" \
-	&& echo "${checksum} /tmp/oras.tar.gz" | sha256sum -c \
-	&& tar -xvf "/tmp/oras.tar.gz" --no-same-permissions --no-same-owner -C "/tmp" \
-	&& install -o "root" -g "root" -m "0755" "/tmp/oras" "/tmp/local/bin/oras"
+	RUN case "${TARGETARCH}" in \
+	'amd64') \
+		compose_checksum="${DOCKER_COMPOSE_CHECKSUM}"; \
+		arch="x86_64"; \
+	;; \
+	'arm64') \
+		compose_checksum="${DOCKER_COMPOSE_CHECKSUM_ARM}"; \
+		arch="aarch64"; \
+	;; \
+	*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
+esac; \
+curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-linux-${arch}" -o "/tmp/docker-compose" \
+&& echo "${compose_checksum} /tmp/docker-compose" | sha256sum -c \
+&& install -o "root" -g "root" -m "0755" "/tmp/docker-compose" "/tmp/local/lib/docker/cli-plugins/docker-compose" \
+&& install -o "root" -g "root" -m "0755" "/tmp/docker-compose" "/tmp/local/bin/docker-compose"
 
 COPY ./docker_helpers.sh /tmp/local/lib
 
