feat: update tools versions

diff --git a/containers/base/Dockerfile b/containers/base/Dockerfile
--- a/containers/base/Dockerfile
+++ b/containers/base/Dockerfile
@@ -9,9 +9,9 @@ ARG COSIGN_CHECKSUM=10dab2fd2170b5aa0d5c0673a9a2793304960220b314f6a873bf39c2f082
 ARG COSIGN_CHECKSUM_ARM=c12fc6150195758ec0b1aeb1aade3381a1d3a299584982b66543f22bab04535b
 
 # https://github.com/anchore/syft/releases
-ARG SYFT_VERSION=1.40.0
-ARG SYFT_CHECKSUM=f551cd16da3a5456f5245bb8045b98594263a678a9d2a07b462a05be0357b795
-ARG SYFT_CHECKSUM_ARM=1d62e6c40d23c319e113514dae3cf84375f4aa93520a46cb01b6ad4e8183f9dd
+ARG SYFT_VERSION=1.40.1
+ARG SYFT_CHECKSUM=c229137c919f22aa926c1c015388db5ec64e99c078e0baac053808e8f36e2e00
+ARG SYFT_CHECKSUM_ARM=13c03a712ad496083d164bdd009c458fda854fb4c8456441fc9c286bbb500e07
 
 # https://github.com/oras-project/oras/releases
 ARG ORAS_VERSION=1.3.0
@@ -28,26 +28,26 @@ USER root
 RUN mkdir -p "/tmp/local/bin" "/tmp/local/lib"
 
 RUN case "${TARGETARCH}" in \
-		'amd64') \
-			cosign_checksum="${COSIGN_CHECKSUM}"; \
-		;; \
-		'arm64') \
-			cosign_checksum="${COSIGN_CHECKSUM_ARM}"; \
-		;; \
-		*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
+	'amd64') \
+	cosign_checksum="${COSIGN_CHECKSUM}"; \
+	;; \
+	'arm64') \
+	cosign_checksum="${COSIGN_CHECKSUM_ARM}"; \
+	;; \
+	*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
 	esac; \
 	curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-${TARGETARCH}" -o "/tmp/cosign" \
 	&& echo "${cosign_checksum} /tmp/cosign" | sha256sum -c \
 	&& install -o "root" -g "root" -m "0755" "/tmp/cosign" "/tmp/local/bin/cosign"
 
 RUN case "${TARGETARCH}" in \
-		'amd64') \
-			syft_checksum="${SYFT_CHECKSUM}"; \
-		;; \
-		'arm64') \
-			syft_checksum="${SYFT_CHECKSUM_ARM}"; \
-		;; \
-		*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
+	'amd64') \
+	syft_checksum="${SYFT_CHECKSUM}"; \
+	;; \
+	'arm64') \
+	syft_checksum="${SYFT_CHECKSUM_ARM}"; \
+	;; \
+	*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
 	esac; \
 	curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/anchore/syft/releases/download/v${SYFT_VERSION}/syft_${SYFT_VERSION}_linux_${TARGETARCH}.tar.gz" -o "/tmp/syft.tar.gz" \
 	&& echo "${syft_checksum} /tmp/syft.tar.gz" | sha256sum -c \
@@ -56,30 +56,30 @@ RUN case "${TARGETARCH}" in \
 
 RUN case "${TARGETARCH}" in \
 	'amd64') \
-		checksum="${ORAS_CHECKSUM}"; \
+	checksum="${ORAS_CHECKSUM}"; \
 	;; \
 	'arm64') \
-		checksum="${ORAS_CHECKSUM_ARM}"; \
+	checksum="${ORAS_CHECKSUM_ARM}"; \
 	;; \
 	*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
-esac; \
-curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/oras-project/oras/releases/download/v${ORAS_VERSION}/oras_${ORAS_VERSION}_linux_${TARGETARCH}.tar.gz" -o "/tmp/oras.tar.gz" \
-&& echo "${checksum} /tmp/oras.tar.gz" | sha256sum -c \
-&& tar -xvf "/tmp/oras.tar.gz" --no-same-permissions --no-same-owner -C "/tmp" \
-&& install -o "root" -g "root" -m "0755" "/tmp/oras" "/tmp/local/bin/oras"
+	esac; \
+	curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/oras-project/oras/releases/download/v${ORAS_VERSION}/oras_${ORAS_VERSION}_linux_${TARGETARCH}.tar.gz" -o "/tmp/oras.tar.gz" \
+	&& echo "${checksum} /tmp/oras.tar.gz" | sha256sum -c \
+	&& tar -xvf "/tmp/oras.tar.gz" --no-same-permissions --no-same-owner -C "/tmp" \
+	&& install -o "root" -g "root" -m "0755" "/tmp/oras" "/tmp/local/bin/oras"
 
 RUN case "${TARGETARCH}" in \
 	'amd64') \
-		checksum="${YQ_CHECKSUM}"; \
+	checksum="${YQ_CHECKSUM}"; \
 	;; \
 	'arm64') \
-		checksum="${YQ_CHECKSUM_ARM}"; \
+	checksum="${YQ_CHECKSUM_ARM}"; \
 	;; \
 	*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
-esac; \
-curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_${TARGETARCH}" -o "/tmp/yq" \
-&& echo "${checksum} /tmp/yq" | sha256sum -c \
-&& install -o "root" -g "root" -m "0755" "/tmp/yq" "/tmp/local/bin/yq"
+	esac; \
+	curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_${TARGETARCH}" -o "/tmp/yq" \
+	&& echo "${checksum} /tmp/yq" | sha256sum -c \
+	&& install -o "root" -g "root" -m "0755" "/tmp/yq" "/tmp/local/bin/yq"
 
 COPY ./base_helpers.sh /tmp/local/lib
 
diff --git a/containers/docker/Dockerfile b/containers/docker/Dockerfile
--- a/containers/docker/Dockerfile
+++ b/containers/docker/Dockerfile
@@ -4,7 +4,7 @@ FROM docker.io/curlimages/curl:8.18.0@sha256:d94d07ba9e7d6de898b6d96c1a072f6f826
 ARG TARGETARCH
 
 # https://download.docker.com/linux/static/stable/
-ARG DOCKER_VERSION=29.1.4
+ARG DOCKER_VERSION=29.1.5
 
 # https://github.com/docker/buildx/releases
 ARG BUILDX_VERSION=v0.30.1
@@ -26,33 +26,33 @@ RUN arch="$(uname -m)"; \
 	&& install -o "root" -g "root" -m "0755" "/tmp/docker/docker" "/tmp/local/bin/docker"
 
 RUN case "${TARGETARCH}" in \
-		'amd64') \
-			buildx_checksum="${BUILDX_CHECKSUM}"; \
-		;; \
-		'arm64') \
-			buildx_checksum="${BUILDX_CHECKSUM_ARM}"; \
-		;; \
-		*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
+	'amd64') \
+	buildx_checksum="${BUILDX_CHECKSUM}"; \
+	;; \
+	'arm64') \
+	buildx_checksum="${BUILDX_CHECKSUM_ARM}"; \
+	;; \
+	*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
 	esac; \
 	curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-${TARGETARCH}" -o "/tmp/docker-buildx" \
 	&& echo "${buildx_checksum} /tmp/docker-buildx" | sha256sum -c \
 	&& install -o "root" -g "root" -m "0755" "/tmp/docker-buildx" "/tmp/local/lib/docker/cli-plugins/docker-buildx"
 
-	RUN case "${TARGETARCH}" in \
+RUN case "${TARGETARCH}" in \
 	'amd64') \
-		compose_checksum="${DOCKER_COMPOSE_CHECKSUM}"; \
-		arch="x86_64"; \
+	compose_checksum="${DOCKER_COMPOSE_CHECKSUM}"; \
+	arch="x86_64"; \
 	;; \
 	'arm64') \
-		compose_checksum="${DOCKER_COMPOSE_CHECKSUM_ARM}"; \
-		arch="aarch64"; \
+	compose_checksum="${DOCKER_COMPOSE_CHECKSUM_ARM}"; \
+	arch="aarch64"; \
 	;; \
 	*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
-esac; \
-curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-linux-${arch}" -o "/tmp/docker-compose" \
-&& echo "${compose_checksum} /tmp/docker-compose" | sha256sum -c \
-&& install -o "root" -g "root" -m "0755" "/tmp/docker-compose" "/tmp/local/lib/docker/cli-plugins/docker-compose" \
-&& install -o "root" -g "root" -m "0755" "/tmp/docker-compose" "/tmp/local/bin/docker-compose"
+	esac; \
+	curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-linux-${arch}" -o "/tmp/docker-compose" \
+	&& echo "${compose_checksum} /tmp/docker-compose" | sha256sum -c \
+	&& install -o "root" -g "root" -m "0755" "/tmp/docker-compose" "/tmp/local/lib/docker/cli-plugins/docker-compose" \
+	&& install -o "root" -g "root" -m "0755" "/tmp/docker-compose" "/tmp/local/bin/docker-compose"
 
 COPY ./docker_helpers.sh /tmp/local/lib
 
diff --git a/containers/go/Dockerfile b/containers/go/Dockerfile
--- a/containers/go/Dockerfile
+++ b/containers/go/Dockerfile
@@ -4,9 +4,9 @@ FROM docker.io/curlimages/curl:8.18.0@sha256:d94d07ba9e7d6de898b6d96c1a072f6f826
 ARG TARGETARCH
 
 # https://go.dev/dl
-ARG GO_VERSION=1.25.5
-ARG GO_CHECKSUM=9e9b755d63b36acf30c12a9a3fc379243714c1c6d3dd72861da637f336ebb35b
-ARG GO_CHECKSUM_ARM=b00b694903d126c588c378e72d3545549935d3982635ba3f7a964c9fa23fe3b9
+ARG GO_VERSION=1.25.6
+ARG GO_CHECKSUM=f022b6aad78e362bcba9b0b94d09ad58c5a70c6ba3b7582905fababf5fe0181a
+ARG GO_CHECKSUM_ARM=738ef87d79c34272424ccdf83302b7b0300b8b096ed443896089306117943dd5
 
 # the 2.x version will be available only from the 1.25 release
 # https://github.com/golangci/golangci-lint/releases
@@ -24,26 +24,26 @@ USER root
 RUN mkdir -p "/tmp/local/bin"
 
 RUN case "${TARGETARCH}" in \
-		'amd64') \
-			go_checksum="${GO_CHECKSUM}"; \
-		;; \
-		'arm64') \
-			go_checksum="${GO_CHECKSUM_ARM}"; \
-		;; \
-		*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
+	'amd64') \
+	go_checksum="${GO_CHECKSUM}"; \
+	;; \
+	'arm64') \
+	go_checksum="${GO_CHECKSUM_ARM}"; \
+	;; \
+	*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
 	esac; \
 	curl -fsSL --proto '=https' --tlsv1.2 "https://go.dev/dl/go${GO_VERSION}.linux-${TARGETARCH}.tar.gz" -o "/tmp/go.tar.gz" \
 	&& echo "${go_checksum} /tmp/go.tar.gz" | sha256sum -c \
 	&& tar -xvf "/tmp/go.tar.gz" --no-same-permissions --no-same-owner -C "/tmp/local"
 
 RUN case "${TARGETARCH}" in \
-		'amd64') \
-			lint_checksum="${LINT_CHECKSUM}"; \
-		;; \
-		'arm64') \
-			lint_checksum="${LINT_CHECKSUM_ARM}"; \
-		;; \
-		*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
+	'amd64') \
+	lint_checksum="${LINT_CHECKSUM}"; \
+	;; \
+	'arm64') \
+	lint_checksum="${LINT_CHECKSUM_ARM}"; \
+	;; \
+	*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
 	esac; \
 	curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_VERSION}/golangci-lint-${GOLANGCI_VERSION}-linux-${TARGETARCH}.tar.gz" -o "/tmp/golangci-lint.tar.gz" \
 	&& echo "${lint_checksum} /tmp/golangci-lint.tar.gz" | sha256sum -c \
@@ -51,15 +51,15 @@ RUN case "${TARGETARCH}" in \
 	&& install -o "root" -g "root" -m "0755" "/tmp/golangci-lint-${GOLANGCI_VERSION}-linux-${TARGETARCH}/golangci-lint" "/tmp/local/bin/golangci-lint"
 
 RUN case "${TARGETARCH}" in \
-		'amd64') \
-			goreleaser_checksum="${GORELEASER_CHECKSUM}"; \
-			goreleaser_arch="x86_64"; \
-		;; \
-		'arm64') \
-			goreleaser_checksum="${GORELEASER_CHECKSUM_ARM}"; \
-			goreleaser_arch="${TARGETARCH}"; \
-		;; \
-		*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
+	'amd64') \
+	goreleaser_checksum="${GORELEASER_CHECKSUM}"; \
+	goreleaser_arch="x86_64"; \
+	;; \
+	'arm64') \
+	goreleaser_checksum="${GORELEASER_CHECKSUM_ARM}"; \
+	goreleaser_arch="${TARGETARCH}"; \
+	;; \
+	*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
 	esac; \
 	curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/goreleaser/goreleaser/releases/download/${GORELEASER_VERSION}/goreleaser_Linux_${goreleaser_arch}.tar.gz" -o "/tmp/goreleaser.tar.gz" \
 	&& echo "${goreleaser_checksum} /tmp/goreleaser.tar.gz" | sha256sum -c \
diff --git a/containers/kubernetes/Dockerfile b/containers/kubernetes/Dockerfile
--- a/containers/kubernetes/Dockerfile
+++ b/containers/kubernetes/Dockerfile
@@ -34,26 +34,26 @@ USER root
 RUN mkdir -p "/tmp/local/bin"
 
 RUN case "${TARGETARCH}" in \
-		'amd64') \
-			kubectl_checksum="${KUBECTL_CHECKSUM}"; \
-		;; \
-		'arm64') \
-			kubectl_checksum="${KUBECTL_CHECKSUM_ARM}"; \
+	'amd64') \
+	kubectl_checksum="${KUBECTL_CHECKSUM}"; \
 	;; \
-		*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
+	'arm64') \
+	kubectl_checksum="${KUBECTL_CHECKSUM_ARM}"; \
+	;; \
+	*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
 	esac; \
 	curl -fsSL --proto '=https' --tlsv1.2 "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/${TARGETARCH}/kubectl" -o "/tmp/kubectl" \
 	&& echo "${kubectl_checksum} /tmp/kubectl" | sha256sum -c \
 	&& install -o "root" -g "root" -m "0755" "/tmp/kubectl" "/tmp/local/bin/kubectl"
 
 RUN case "${TARGETARCH}" in \
-		'amd64') \
-			kustomize_checksum="${KUSTOMIZE_CHECKSUM}"; \
-		;; \
-		'arm64') \
-			kustomize_checksum="${KUSTOMIZE_CHECKSUM_ARM}"; \
+	'amd64') \
+	kustomize_checksum="${KUSTOMIZE_CHECKSUM}"; \
 	;; \
-		*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
+	'arm64') \
+	kustomize_checksum="${KUSTOMIZE_CHECKSUM_ARM}"; \
+	;; \
+	*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
 	esac; \
 	curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_${TARGETARCH}.tar.gz" -o "/tmp/kustomize.tar.gz" \
 	&& echo "${kustomize_checksum} /tmp/kustomize.tar.gz" | sha256sum -c \
@@ -61,13 +61,13 @@ RUN case "${TARGETARCH}" in \
 	&& install -o "root" -g "root" -m "0755" "/tmp/kustomize" "/tmp/local/bin/kustomize"
 
 RUN case "${TARGETARCH}" in \
-		'amd64') \
-			helm_checksum="${HELM_CHECKSUM}"; \
-		;; \
-		'arm64') \
-			helm_checksum="${HELM_CHECKSUM_ARM}"; \
+	'amd64') \
+	helm_checksum="${HELM_CHECKSUM}"; \
 	;; \
-		*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
+	'arm64') \
+	helm_checksum="${HELM_CHECKSUM_ARM}"; \
+	;; \
+	*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
 	esac; \
 	curl -fsSL --proto '=https' --tlsv1.2 "https://get.helm.sh/helm-${HELM_VERSION}-linux-${TARGETARCH}.tar.gz" -o "/tmp/helm.tar.gz" \
 	&& echo "${helm_checksum} /tmp/helm.tar.gz" | sha256sum -c \
@@ -75,26 +75,26 @@ RUN case "${TARGETARCH}" in \
 	&& install -o "root" -g "root" -m "0755" "/tmp/linux-${TARGETARCH}/helm" "/tmp/local/bin/helm"
 
 RUN case "${TARGETARCH}" in \
-		'amd64') \
-			mlp_checksum="${MLP_CHECKSUM}"; \
-		;; \
-		'arm64') \
-			mlp_checksum="${MLP_CHECKSUM_ARM}"; \
+	'amd64') \
+	mlp_checksum="${MLP_CHECKSUM}"; \
 	;; \
-		*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
+	'arm64') \
+	mlp_checksum="${MLP_CHECKSUM_ARM}"; \
+	;; \
+	*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
 	esac; \
 	curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/mia-platform/mlp/releases/download/${MLP_VERSION}/mlp-linux-${TARGETARCH}" -o "/tmp/mlp" \
 	&& echo "${mlp_checksum} /tmp/mlp" | sha256sum -c \
 	&& install -o "root" -g "root" -m "0755" "/tmp/mlp" "/tmp/local/bin/mlp"
 
 RUN case "${TARGETARCH}" in \
-		'amd64') \
-			vab_checksum="${VAB_CHECKSUM}"; \
-		;; \
-		'arm64') \
-			vab_checksum="${VAB_CHECKSUM_ARM}"; \
+	'amd64') \
+	vab_checksum="${VAB_CHECKSUM}"; \
 	;; \
-		*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
+	'arm64') \
+	vab_checksum="${VAB_CHECKSUM_ARM}"; \
+	;; \
+	*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
 	esac; \
 	curl -fsSL --proto '=https' --tlsv1.2 "https://github.com/mia-platform/vab/releases/download/${VAB_VERSION}/vab-linux-${TARGETARCH}" -o "/tmp/vab" \
 	&& echo "${vab_checksum} /tmp/vab" | sha256sum -c \
diff --git a/containers/node/Dockerfile b/containers/node/Dockerfile
--- a/containers/node/Dockerfile
+++ b/containers/node/Dockerfile
@@ -13,15 +13,15 @@ USER root
 RUN mkdir -p "/tmp/local/bin"
 
 RUN case "${TARGETARCH}" in \
-		'amd64') \
-			checksum="${NODE_CHECKSUM}"; \
-			arch="x64"; \
-		;; \
-		'arm64') \
-			checksum="${NODE_CHECKSUM_ARM}"; \
-			arch="${TARGETARCH}"; \
-		;; \
-		*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
+	'amd64') \
+	checksum="${NODE_CHECKSUM}"; \
+	arch="x64"; \
+	;; \
+	'arm64') \
+	checksum="${NODE_CHECKSUM_ARM}"; \
+	arch="${TARGETARCH}"; \
+	;; \
+	*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1; ;; \
 	esac; \
 	curl -fsSL --proto '=https' --tlsv1.2 "https://nodejs.org/download/release/${NODE_VERSION}/node-${NODE_VERSION}-linux-${arch}.tar.xz" -o "/tmp/node.tar.xz" \
 	&& echo "${checksum} /tmp/node.tar.xz" | sha256sum -c - \
diff --git a/containers/sysdig/Dockerfile b/containers/sysdig/Dockerfile
--- a/containers/sysdig/Dockerfile
+++ b/containers/sysdig/Dockerfile
@@ -13,13 +13,13 @@ USER root
 RUN mkdir -p "/tmp/local/bin"
 
 RUN case "${TARGETARCH}" in \
-		'amd64') \
-			checksum="${SYSDIG_SCANNER_CHECKSUM}"; \
-		;; \
-		'arm64') \
-			checksum="${SYSDIG_SCANNER_CHECKSUM_ARM}"; \
-		;; \
-		*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1 ;; \
+	'amd64') \
+	checksum="${SYSDIG_SCANNER_CHECKSUM}"; \
+	;; \
+	'arm64') \
+	checksum="${SYSDIG_SCANNER_CHECKSUM_ARM}"; \
+	;; \
+	*) echo >&2 "error: unsupported architecture ($TARGETARCH)"; exit 1 ;; \
 	esac; \
 	curl -fsSL --proto '=https' --tlsv1.2 "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/${SYSDIG_SCANNER_VERSION}/linux/${TARGETARCH}/sysdig-cli-scanner" -o "/tmp/sysdig-cli-scanner" \
 	&& echo "${checksum} /tmp/sysdig-cli-scanner" | sha256sum -c \
